"""Added Item Field to Post

Revision ID: 1a62111f01df
Revises: 383d275db97c
Create Date: 2015-05-19 20:26:13.087219

"""

# revision identifiers, used by Alembic.
revision = '1a62111f01df'
down_revision = '383d275db97c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('item', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'item')
    ### end Alembic commands ###
