"""post category

Revision ID: 35e7dbb4ca87
Revises: 250c51e9cd9
Create Date: 2015-05-19 07:34:52.289178

"""

# revision identifiers, used by Alembic.
revision = '35e7dbb4ca87'
down_revision = '250c51e9cd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    ### end Alembic commands ###
