"""Added New Fields to Post

Revision ID: 383d275db97c
Revises: 35e7dbb4ca87
Create Date: 2015-05-19 19:45:06.443684

"""

# revision identifiers, used by Alembic.
revision = '383d275db97c'
down_revision = '35e7dbb4ca87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('contact', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('price', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('sold', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sold')
    op.drop_column('posts', 'price')
    op.drop_column('posts', 'contact')
    ### end Alembic commands ###
